services:
  redis-app:
    image: redis:7.0.14
    container_name: redis-app
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes", "--maxmemory-policy", "allkeys-lru"]
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  default:
    name: hhplus-jaeho
    driver: bridge
